# Generated by Django 4.0.4 on 2022-05-31 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VaccineApp',
            fields=[
                ('PatientId', models.AutoField(primary_key=True, serialize=False)),
                ('PatientFirstName', models.CharField(max_length=500)),
                ('PatientLastName', models.CharField(max_length=500)),
                ('PatientDateOfBirth', models.DateField()),
                ('PatientAdress', models.CharField(max_length=500)),
                ('PatientCity', models.CharField(max_length=500)),
                ('PatientZip', models.IntegerField(max_length=500)),
                ('PatientLand', models.CharField(max_length=500)),
                ('PatientCell', models.IntegerField()),
                ('PatientInfected', models.BooleanField()),
                ('PatientDiabetes', models.BooleanField()),
                ('PatientCardio', models.BooleanField()),
                ('PatientAllergies', models.BooleanField()),
                ('PatientOther', models.CharField(max_length=500)),
            ],
        ),
    ]
