# Generated by Django 4.0.4 on 2022-06-02 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VaccineApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccineapp',
            name='PatientZip',
            field=models.IntegerField(),
        ),
    ]
