# Generated by Django 4.0.4 on 2022-06-02 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VaccineApp', '0003_alter_vaccineapp_patientother'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccineapp',
            name='PatientCell',
            field=models.CharField(max_length=50),
        ),
    ]
